# application.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

jolt:
  specification: |
    [
      {
        "operation": "shift",
        "spec": {
          "client": {
            "name": "companyName",
            "address": {
              "street": "clientStreetAddress",
              "state": "clientAddressState"
            },
            "employeeDetails": {
              "name": "employee.name",
              "designation": "employee.designation",
              "phone": "employee.contact.phone",
              "home": "employee.contact.home",
              "address": "employee.contact.address"
            }
          }
        }
      },
      {
        "operation": "modify-overwrite-beta",
        "spec": {
          "address": "=concat(@(1,clientStreetAddress),' ',@(1,clientAddressState))"
        }
      },
      {
        "operation": "remove",
        "spec": {
          "clientStreetAddress": "",
          "clientAddressState": ""
        }
      }
    ]
